# Generated by Django 3.2.3 on 2021-05-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
