from django.contrib import admin
from .models import Post, Comment
# Register your models here.


# This decorator does the same thing as 
# the admin.site.register() function
@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    #determines what fields are displayed on the admin panel
    list_display = ('title', 'slug', 'author', 'publish', 'status')
    
    #adds filters to admin panel based on provided fields
    list_filter = ('status', 'created', 'publish', 'author')
    
    #tuple that determines which fields are searched when a search value is entered
    search_fields = ('title', 'body')
    
    #the field is autogenerated based on the content of the field specified as the value
    prepopulated_fields = {'slug': ('title',)}
    
    #provides a lookup widget for the author field
    #this scales much better than the default dropdown menu
    #for example when we have thousands of users
    raw_id_fields = ('author',)
    
    #adds navigation links to specific publish dates
    date_hierarchy = 'publish'
    
    #determines sorting criteria, in this case ordered by status then publish date
    ordering = ('status', 'publish')

@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin):
    list_display = ('name','email','post', 'created', 'active')
    list_filter = ('active', 'created', 'updated')
    search_fields = ('name', 'email', 'body')